"""2-D activation analysis of one MLP hidden neuron (docs/dev/INTERFACES.md §5).

Split out of ``mlp_mechanism`` so that neither file grows past the 800-line limit; the
public entry point ``activation_analysis`` is re-exported by ``mlp_mechanism`` and is part
of that module's documented API.

THE OBJECT
----------
For hidden neuron ``i`` the MLP's pre-activation is *exactly* additive::

    act[a, b, i] = ReLU(u_a[a, i] + u_b[b, i] + b_in[i])

so the whole 2-D structure of a neuron is generated by two 1-D curves and one scalar.
Everything here is measured on the full ``p x p`` grid of that map.

WHAT IS MEASURED, AND WHAT IT DOES *NOT* SHOW
---------------------------------------------
Rectifying ``cos(w_k a - phi_a) + cos(w_k b - phi_b)`` produces an ``(a+b)`` cross term of
amplitude ``8/(3 pi^2)`` **and an ``(a-b)`` cross term of exactly the same amplitude**
(``docs/MLP_MECHANISM_DERIVATION.md`` §4.1, verified in ``tests/test_derivations.py``):
``|cos s| |cos t|`` is symmetric in ``s = (u+v)/2`` and ``t = (u-v)/2``. A single circuit
neuron is therefore *expected* to show ``sum_direction_share ~= diff_direction_share``, and
that is **not** evidence against the mechanism. Addition is selected by the population
together with the readout (coherent addition under ``phi_out = phi_a + phi_b``), and the
sum-over-difference contrast is tested on the LOGITS in ``analysis/logit_formula_fit``
(``control_difference``), never here. The per-neuron sum/diff shares below are reported
**descriptively** and are never a pass criterion. (INTERFACES §5 carried the opposite,
false prediction until its 2026-09-03 correction.)

The per-neuron falsifiable prediction lives in ``mlp_mechanism.phase_relation``.

Reported per neuron
-------------------
==============================  =========================================================
key                             definition
==============================  =========================================================
``power2d``                     ``fwd2d(act)^2`` — power of every 2-D Fourier mode (i, j)
``top_mode_{i,j,share}``        the 5 strongest modes, constant mode (0,0) excluded
``same_frequency_block_share``  power in the same-frequency 2x2 blocks / non-constant power
``sum_direction_share``         power in ``cos/sin(w_k(a+b))`` of the key set / non-const.
``diff_direction_share``        power in ``cos/sin(w_k(a-b))`` of the key set / non-const.
``ev_sum`` / ``ev_diff``        ``Var(E[act | a+b]) / Var(act)`` and the (a-b) counterpart
``swap_symmetry``               ``corr(act[a,b], act[b,a])`` — 1 iff phi_a = phi_b
``ev_hypothesized_*``           R^2 of ``act`` against ``ReLU(fit_a + fit_b + b_in)``
``dead``                        ``max_{a,b} act <= 0``
==============================  =========================================================

A dead neuron has zero activation variance: ``swap_symmetry`` and every ``R^2`` are then
undefined and reported as ``NaN`` — never as a substitute value (INTERFACES §0).
"""
from __future__ import annotations

import numpy as np

from . import mask_protocols
from .fourier import fourier_basis
from .progress_measures import fwd2d

MODULE_VERSION = "1.0"

#: Neurons whose full 2-D spectrum is stored in the npz (INTERFACES §5: "up to 16").
N_EXEMPLARS = 16
#: How many (i, j) modes are reported per neuron.
N_TOP_MODES = 5
#: Neurons per chunk of the grid loop: the full act tensor is [p, p, d_mlp] float64
#: (52 MB at p=113, d_mlp=512) and fwd2d needs two more of that size, so the loop is
#: chunked. The chunk size changes nothing but peak memory (asserted in the tests).
CHUNK = 128
#: Waveform models of ``wave_fitting`` used for ``ev_hypothesized``.
HYPOTHESIS_MODELS: tuple[str, ...] = ("sinusoid", "square")
#: Rule by which the exemplar neurons are picked, echoed in ``params``.
EXEMPLAR_RULE = "largest_activation_variance_among_live_neurons"


# --------------------------------------------------------------------------- #
# Fourier-plane helpers                                                        #
# --------------------------------------------------------------------------- #
def _cos_sin_rows(p: int) -> tuple[np.ndarray, np.ndarray]:
    """Row indices of ``(cos_k, sin_k)`` for ``k = 1..(p-1)//2`` in the fourier_basis layout."""
    half = (p - 1) // 2
    k = np.arange(1, half + 1)
    return 1 + 2 * (k - 1), 2 + 2 * (k - 1)


def _block_entries(Ahat: np.ndarray, p: int) -> tuple[np.ndarray, ...]:
    """The four same-frequency block entries per frequency: ``A, B, C, D`` each ``[half, n]``.

    ``A = Ahat[cos_k, cos_k]``, ``B = Ahat[sin_k, sin_k]``, ``C = Ahat[sin_k, cos_k]``,
    ``D = Ahat[cos_k, sin_k]`` — the module docstring of ``mask_protocols`` derives that
    ``cos/sin(w_k(a+b))`` spans ``(A, B, C, D) = (1,-1,0,0), (0,0,1,1)`` and the difference
    directions ``(1,1,0,0), (0,0,1,-1)``.
    """
    ci, si = _cos_sin_rows(p)
    return Ahat[ci, ci], Ahat[si, si], Ahat[si, ci], Ahat[ci, si]


def _sum_diff_power(Ahat: np.ndarray, p: int) -> tuple[np.ndarray, np.ndarray]:
    """Per frequency ``k``: power of ``Ahat`` in the (a+b) and in the (a-b) directions.

    Orthogonal decomposition of each 4-D block: ``(A-B)^2/2 + (C+D)^2/2`` lies in the sum
    subspace, ``(A+B)^2/2 + (C-D)^2/2`` in the difference subspace, and the two add up to
    ``A^2+B^2+C^2+D^2``. Both are ``[half, n]``.

    NOTE (2026-09-03): ``mask_protocols`` ships ``SumDirectionsOnly`` but **no**
    ``DiffDirectionsOnly`` — INTERFACES §5 asks for one, but ``mask_protocols.py`` is owned
    by another work package and is not edited from here. The difference projection is
    therefore implemented locally, as the exact ``(a-b)`` counterpart of
    ``SumDirectionsOnly._project``. ``sum_projection_agreement`` cross-checks the sum half
    against the shipped operator and ``diff_projection_source`` records which
    implementation was used, so the substitution is visible in every output file.
    """
    A, B, C, D = _block_entries(Ahat, p)
    sum_power = ((A - B) ** 2 + (C + D) ** 2) / 2.0
    diff_power = ((A + B) ** 2 + (C - D) ** 2) / 2.0
    return sum_power, diff_power


def diff_projection_source() -> str:
    """Which ``(a-b)`` projection is in use — the shipped operator if it ever appears."""
    return ("mask_protocols.DiffDirectionsOnly"
            if hasattr(mask_protocols, "DiffDirectionsOnly")
            else "local _sum_diff_power (mask_protocols has no DiffDirectionsOnly)")


def _protocol_sum_power(Ahat: np.ndarray, p: int, key_freqs) -> np.ndarray:
    """Sum-direction power of the key set through ``mask_protocols.SumDirectionsOnly``.

    Used as an independent check of the analytic block formula: ``restrict`` keeps the
    constant, which is removed here, so the remaining squared norm is exactly the key set's
    sum-direction power.
    """
    proto = mask_protocols.SumDirectionsOnly(p, key_freqs)
    kept = proto.restrict(Ahat)
    kept[0, 0] = 0.0
    return (kept ** 2).sum(axis=(0, 1))


def _mode_kind(i, j) -> np.ndarray:
    """Label every ``(i, j)`` mode index pair: constant / single-axis / same- / cross-frequency."""
    i, j = np.asarray(i), np.asarray(j)
    fi, fj = (i + 1) // 2, (j + 1) // 2                 # 0 for the constant row
    out = np.full(i.shape, "cross_frequency", dtype=object)
    out = np.where((fi == 0) & (fj == 0), "constant", out)
    out = np.where((fi != 0) & (fj == 0), "single_axis_a", out)
    out = np.where((fi == 0) & (fj != 0), "single_axis_b", out)
    out = np.where((fi != 0) & (fj != 0) & (fi == fj), "same_frequency", out)
    return out


# --------------------------------------------------------------------------- #
# per-chunk measurements                                                       #
# --------------------------------------------------------------------------- #
def _r2(act: np.ndarray, pred: np.ndarray, ss_tot: np.ndarray) -> np.ndarray:
    """``1 - RSS/TSS`` per neuron over the grid; ``NaN`` where the activation has no variance."""
    rss = ((act - pred) ** 2).sum(axis=(0, 1))
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(ss_tot > 0, 1.0 - rss / ss_tot, np.nan)


def _swap_symmetry(act: np.ndarray, ss_tot: np.ndarray, mean: np.ndarray) -> np.ndarray:
    """``corr(act[a,b], act[b,a])``: both sides share mean and variance, so it is a ratio."""
    cross = ((act - mean) * (np.swapaxes(act, 0, 1) - mean)).sum(axis=(0, 1))
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(ss_tot > 0, cross / ss_tot, np.nan)


def _top_modes(power2d: np.ndarray, p: int, n_top: int):
    """The ``n_top`` strongest ``(i, j)`` modes per column, the constant mode (0,0) EXCLUDED.

    The constant carries most of a rectified neuron's power and says nothing about the
    circuit, so it is dropped here and reported separately as ``constant_share``.
    """
    flat = power2d.reshape(p * p, -1).copy()
    flat[0] = -1.0                                      # drop (0, 0)
    part = np.argpartition(-flat, n_top, axis=0)[:n_top]
    cols = np.arange(flat.shape[1])[None, :]
    order = np.argsort(-flat[part, cols], axis=0)
    idx = np.take_along_axis(part, order, axis=0)       # [n_top, n]
    return idx // p, idx % p, flat[idx, cols]


def _chunk_measurements(act: np.ndarray, Fb: np.ndarray, p: int, key_rows,
                        preds: dict, b_in: np.ndarray) -> dict:
    """Every per-neuron scalar of one chunk of neurons, plus its 2-D power spectra."""
    mean = act.mean(axis=(0, 1))
    ss_tot = ((act - mean) ** 2).sum(axis=(0, 1))
    Ahat = fwd2d(act, Fb)
    power2d = Ahat ** 2
    const_power = power2d[0, 0]
    total = power2d.sum(axis=(0, 1))
    nonconst = total - const_power

    A, B, C, D = _block_entries(Ahat, p)
    block_power = A ** 2 + B ** 2 + C ** 2 + D ** 2                   # [half, m]
    sum_power, diff_power = _sum_diff_power(Ahat, p)
    ki = np.asarray(key_rows, dtype=np.int64) - 1                     # 0-based frequency index
    i_top, j_top, p_top = _top_modes(power2d, p, N_TOP_MODES)

    with np.errstate(divide="ignore", invalid="ignore"):
        def share(x):
            return np.where(nonconst > 0, x / nonconst, np.nan)

        out = {
            "power2d": power2d,
            "activation_mean": mean,
            "activation_var": ss_tot / (p * p),
            "dead": act.max(axis=(0, 1)) <= 0.0,
            "constant_share": np.where(total > 0, const_power / total, np.nan),
            "same_frequency_block_share": share(block_power.sum(axis=0)),
            "same_frequency_block_share_key_freqs": share(block_power[ki].sum(axis=0)),
            "sum_direction_share": share(sum_power[ki].sum(axis=0)),
            "diff_direction_share": share(diff_power[ki].sum(axis=0)),
            "sum_direction_share_all_freqs": share(sum_power.sum(axis=0)),
            "diff_direction_share_all_freqs": share(diff_power.sum(axis=0)),
            "sum_direction_power_key": sum_power[ki].sum(axis=0),
            "swap_symmetry": _swap_symmetry(act, ss_tot, mean),
            "top_mode_i": i_top, "top_mode_j": j_top,
            "top_mode_share": np.where(nonconst > 0, p_top / nonconst, np.nan),
            "nonconstant_power": nonconst,
        }
    for model, (pa, pb) in preds.items():
        hyp = np.maximum(pa[:, None, :] + pb[None, :, :] + b_in, 0.0)
        out[f"ev_hypothesized_{model}"] = _r2(act, hyp, ss_tot)
    return out


# --------------------------------------------------------------------------- #
# public entry point                                                           #
# --------------------------------------------------------------------------- #
def _act_builder(u_a: np.ndarray, u_b: np.ndarray, b_in: np.ndarray,
                 act: np.ndarray | None = None):
    """Return ``f(cols) -> [p, p, len(cols)]``, the activation of a column selection.

    Default (``act is None``): ``ReLU(u_a + u_b + b_in)``. This IS the MLP's activation
    exactly -- ``models/mlp.py`` has no path by which a and b interact before the ReLU.

    When ``act`` is supplied (``[p, p, n]``) it is sliced instead. The transformer needs
    this: attention makes its pre-activation only *approximately* additive in the effective
    operand curves, so rectifying ``u_a + u_b + c`` is a reconstruction, not the model's
    hidden layer. ``analysis.transformer_mechanism`` passes the true ``hidden`` here and
    reports the reconstruction gap separately as ``additivity_r2`` (INTERFACES 6).

    ``cols`` may be a slice or an integer index array; both index the last axis the same
    way in the two branches.
    """
    if act is None:
        return lambda cols: np.maximum(u_a[:, None, cols] + u_b[None, :, cols] + b_in[cols], 0.0)
    A = np.asarray(act, dtype=np.float64)
    want = (u_a.shape[0], u_a.shape[0], u_a.shape[1])
    if A.shape != want:
        raise ValueError(f"act must be [p, p, n_neurons] = {want}, got {A.shape}")
    return lambda cols: A[:, :, cols]


def activation_analysis(curves: dict, p: int, key_freqs, fits: dict | None = None,
                        n_exemplars: int = N_EXEMPLARS, chunk: int = CHUNK,
                        sum_dependence_result: dict | None = None,
                        act: np.ndarray | None = None) -> dict:
    """INTERFACES §5: the 2-D activation battery per hidden neuron.

    ``curves`` are ``mlp_mechanism.effective_curves``'s ``u_a``, ``u_b`` (``[p, n]``) and
    ``b_in`` (``[n]``); ``key_freqs`` is the key-frequency set the sum/diff shares are read
    on (from ``analysis.key_frequencies``, INTERFACES §4). ``fits`` are
    ``wave_fitting.fit_matrix`` results for ``u_a`` and ``u_b`` (computed here at each
    column's own dominant frequency if not supplied) and provide the ``ev_hypothesized``
    predictions. ``sum_dependence_result`` re-uses an existing ``sum_dependence`` call.

    Returns ``{"per_neuron": {array per neuron}, "exemplars": {...}, "summary": {...},
    "params": {...}}``. The 2-D spectra of at most ``n_exemplars`` neurons are kept;
    everything else is a per-neuron scalar (INTERFACES §0: arrays to the npz, JSON gets
    summaries).
    """
    from .mlp_mechanism import sum_dependence                # local: circular at import time

    u_a = np.asarray(curves["u_a"], dtype=np.float64)
    u_b = np.asarray(curves["u_b"], dtype=np.float64)
    b_in = np.asarray(curves["b_in"], dtype=np.float64).ravel()
    if u_a.shape != u_b.shape or u_a.shape[0] != p:
        raise ValueError(f"u_a {u_a.shape} and u_b {u_b.shape} must both be [p={p}, n]")
    if b_in.shape[0] != u_a.shape[1]:
        raise ValueError(f"b_in has {b_in.shape[0]} entries but there are {u_a.shape[1]} neurons")
    n = u_a.shape[1]
    keys = mask_protocols._validate(p, key_freqs)          # same validation as the protocols
    fits = fits if fits is not None else default_fits(u_a, u_b, p)
    Fb, _ = fourier_basis(p)

    get_act = _act_builder(u_a, u_b, b_in, act)
    per: dict[str, list] = {}
    for start in range(0, n, int(chunk)):
        cols = slice(start, min(start + int(chunk), n))
        preds = {m: (fits["u_a"]["pred"][m][:, cols], fits["u_b"]["pred"][m][:, cols])
                 for m in HYPOTHESIS_MODELS}
        res = _chunk_measurements(get_act(cols), Fb, p, keys, preds, b_in[cols])
        res.pop("power2d")
        for key, value in res.items():
            per.setdefault(key, []).append(value)
    per_neuron = {key: np.concatenate(v, axis=-1) for key, v in per.items()}

    sums = (sum_dependence_result if sum_dependence_result is not None
            else sum_dependence(curves, p, act=act))
    per_neuron["ev_sum"] = np.asarray(sums["variance_explained_by_sum"], dtype=np.float64)
    per_neuron["ev_diff"] = np.asarray(sums["variance_explained_by_diff"], dtype=np.float64)

    exemplars = _exemplar_spectra(get_act, Fb, p, per_neuron, int(n_exemplars))
    check = _sum_projection_agreement(get_act, Fb, p, keys, per_neuron, exemplars["index"])
    params = {"p": int(p), "key_frequencies": [int(k) for k in keys], "n_neurons": int(n),
              "n_top_modes": int(N_TOP_MODES), "n_exemplars": int(n_exemplars),
              "chunk": int(chunk), "exemplar_rule": EXEMPLAR_RULE,
              "hypothesis_models": list(HYPOTHESIS_MODELS),
              "top_modes_exclude_constant": True,
              "activation_source": ("relu(u_a + u_b + b_in) rebuilt from the curves"
                                    if act is None else
                                    "supplied activation tensor (the model's true hidden layer)"),
              "diff_projection_source": diff_projection_source(),
              "sum_projection_check": "mask_protocols.SumDirectionsOnly on the exemplar neurons",
              "per_neuron_sum_vs_diff_is_descriptive": (
                  "MLP_MECHANISM_DERIVATION 4.1: rectification gives the (a+b) and (a-b) cross "
                  "terms EQUAL amplitude 8/(3 pi^2), so sum ~= diff is the prediction for a "
                  "circuit neuron and is never a pass criterion")}
    return {"per_neuron": per_neuron, "exemplars": exemplars,
            "summary": summarize_activation(per_neuron, check), "params": params}


def fit_curve_matrix(Y: np.ndarray, k_per_column, cv_folds: int = 0, seed: int = 0) -> dict:
    """``wave_fitting.fit_matrix``, called once per distinct fundamental and merged.

    Numerically identical to a single ``fit_matrix(Y, k_per_column)`` call — that function
    already fits the columns of one ``k`` as one batch, so splitting the call per ``k``
    changes no design matrix, no phase grid and no fitted number.

    WHY THE SPLIT (2026-09-03). ``fit_matrix`` decides which parameter entries are
    per-column by comparing ``v.shape[-1]`` against the column count of its **first** batch.
    ``odd_harmonics`` carries the constant array ``harmonics = (1, 3, 5, 7)``, so whenever
    the lowest-``k`` group happens to hold exactly four neurons that constant is mistaken
    for a per-column array and the gather raises ``IndexError`` (reproduced at ``p = 23``
    with 48 synthetic neurons, and reachable at ``p = 113`` whenever the smallest dominant
    frequency is shared by exactly four neurons). One group per call cannot trigger it: the
    constant is then reordered within its own length and immediately overwritten by
    ``fit_matrix`` itself. ``wave_fitting.py`` belongs to another work package and is not
    edited from here; the defect is reported instead.
    """
    from .wave_fitting import MODEL_NAMES, fit_matrix

    Y = np.asarray(Y, dtype=np.float64)
    ks = np.broadcast_to(np.atleast_1d(np.asarray(k_per_column)), (Y.shape[1],)).astype(np.int64)
    pieces = [(cols, fit_matrix(Y[:, cols], ks[cols], int(cv_folds), int(seed)))
              for cols in (np.flatnonzero(ks == k) for k in np.unique(ks))]
    inv = np.argsort(np.concatenate([c for c, _ in pieces]), kind="stable")

    def cat(pick):
        return np.concatenate([np.asarray(pick(f)) for _, f in pieces], axis=-1)[..., inv]

    base = pieces[0][1]
    out = {key: base[key] for key in ("p", "models", "n_params", "phase_convention",
                                      "rss_floor", "cv_folds", "seed")}
    out["n_columns"] = int(Y.shape[1])
    out["k"] = cat(lambda f: f["k"])
    for stat in ("rss", "nmse", "r2", "aic", "aicc", "delta_aic"):
        out[stat] = {m: cat(lambda f, s=stat, mm=m: f[s][mm]) for m in MODEL_NAMES}
    out["pred"] = {m: cat(lambda f, mm=m: f["pred"][mm]) for m in MODEL_NAMES}
    out["params"] = {m: {key: (v if key == "harmonics"
                               else cat(lambda f, mm=m, kk=key: f["params"][mm][kk]))
                         for key, v in base["params"][m].items()} for m in MODEL_NAMES}
    out["best_by_aic"] = cat(lambda f: f["best_by_aic"])
    out["best_by_aicc"] = cat(lambda f: f["best_by_aicc"])
    out["delta_aic_sinusoid_minus_square"] = cat(lambda f: f["delta_aic_sinusoid_minus_square"])
    if "cv" in base:
        out["cv"] = {"heldout_nmse_mean": {m: cat(lambda f, mm=m: f["cv"]["heldout_nmse_mean"][mm])
                                           for m in MODEL_NAMES},
                     "best_by_cv": cat(lambda f: f["cv"]["best_by_cv"])}
    return out


def default_fits(u_a: np.ndarray, u_b: np.ndarray, p: int) -> dict:
    """Waveform fits at each column's own dominant frequency, for ``u_a`` and ``u_b``."""
    from .metrics import power_spectrum
    return {name: fit_curve_matrix(Y, power_spectrum(Y, p)["dominant_freq"])
            for name, Y in (("u_a", u_a), ("u_b", u_b))}


def _exemplar_spectra(get_act, Fb, p: int, per_neuron: dict, n_exemplars: int) -> dict:
    """Full 2-D power spectra of the ``n_exemplars`` live neurons with the largest act variance."""
    live = np.flatnonzero(~per_neuron["dead"])
    empty = {"index": np.zeros(0, dtype=np.int64), "power2d": np.zeros((p, p, 0)),
             "rule": EXEMPLAR_RULE, "n": 0}
    if live.size == 0 or int(n_exemplars) <= 0:
        return empty
    order = live[np.argsort(-per_neuron["activation_var"][live], kind="stable")]
    idx = np.sort(order[:int(n_exemplars)])
    return {"index": idx, "power2d": fwd2d(get_act(idx), Fb) ** 2, "rule": EXEMPLAR_RULE,
            "n": int(idx.size)}


def _sum_projection_agreement(get_act, Fb, p: int, keys, per_neuron: dict,
                              idx: np.ndarray) -> dict:
    """Max |analytic - SumDirectionsOnly| sum-direction power over the exemplar neurons."""
    if idx.size == 0:
        return {"n_checked": 0, "max_abs_difference": 0.0, "max_relative_difference": 0.0,
                "operator": "mask_protocols.SumDirectionsOnly"}
    ref = _protocol_sum_power(fwd2d(get_act(idx), Fb), p, keys)
    diff = np.abs(ref - per_neuron["sum_direction_power_key"][idx])
    scale = max(float(np.abs(ref).max()), 1.0)
    return {"n_checked": int(idx.size), "max_abs_difference": float(diff.max()),
            "max_relative_difference": float(diff.max() / scale),
            "operator": "mask_protocols.SumDirectionsOnly"}


def summarize_activation(per_neuron: dict, projection_check: dict) -> dict:
    """JSON-sized distribution summary of the per-neuron arrays (INTERFACES §0)."""
    from .common import summarize as dist

    live = ~per_neuron["dead"]
    scalars = ("same_frequency_block_share", "same_frequency_block_share_key_freqs",
               "sum_direction_share", "diff_direction_share", "sum_direction_share_all_freqs",
               "diff_direction_share_all_freqs", "constant_share", "swap_symmetry",
               "ev_sum", "ev_diff", "activation_mean", "activation_var",
               *(f"ev_hypothesized_{m}" for m in HYPOTHESIS_MODELS))
    out = {"n_neurons": int(per_neuron["dead"].size),
           "n_dead": int((~live).sum()),
           "fraction_dead": float((~live).mean()),
           "sum_projection_check": projection_check}
    for key in scalars:
        out[key] = dist(per_neuron[key][live])
    delta = per_neuron["sum_direction_share"] - per_neuron["diff_direction_share"]
    out["sum_minus_diff_direction_share"] = dist(delta[live])
    out["sum_minus_diff_note"] = ("descriptive only — an ideal circuit neuron predicts ~0 "
                                  "(MLP_MECHANISM_DERIVATION 4.1)")
    kinds = _mode_kind(per_neuron["top_mode_i"][0], per_neuron["top_mode_j"][0])
    names, counts = np.unique(kinds[live].astype(str), return_counts=True)
    out["top_mode_kind_histogram"] = {str(k): int(c) for k, c in zip(names, counts)}
    return out
